module.exports = {
    title: {
        'allClue': '全部供应商线索',
        'publicClue': '公海线索',
        'publicClueDetail': '公海线索详情',
        'underlingClue': '下属的线索',
        'underlingClueDetail': '下属的线索详情',
        'myClue': '我的线索',
        'myClueDetail': '我的线索详情',
        'newClue': '新建供应商线索',
        'editClue': '编辑供应商线索',
        'tosubmit':'提交品控',
        'retosubmit':'重新提交品控',
        'tobeaudited':'品控管理-待审核',
        'qualityadopt':'品控通过',
        'suppliercancel':'品控取消',
        'supplierrefuse':'品控拒绝',
        'audit':'品控审核',
        'supplierlook':'品控查看',
        'updateinfo':'品控更新资料',
        'allsupplier':'全部供应商',
        'modifysupplier':'编辑供应商',
        'mysupplierdetail':'我的供应商详情',
        'inseasupplierdetail':'公海供应商详情',
        'mysupplier':'我的供应商',
        'underlingsupplier':'下属的供应商',
        'inseasupplier':'公海的供应商',
        'underlingsupplierdetail':'下属供应商详情',
        'toFollowUp':'跟进计划',
        'myFollowUp':'我的跟进',
        'followUp':'下属的跟进',
        'allFollowUp':'全部跟进'
    },
    globalName: '奇智SRM管理系统',
};
